### Assigning Clone IDs
Assign clone IDs to each cell and identify multi-cell and single-cell clones.

In [53]:
import numpy as np, pandas as pd
from matplotlib import pyplot as plt
from matplotlib import colors
from matplotlib import figure

### Read in files
CLONE_MAT: Path to .csv file with one cell_BC per line, each column represents presence or absence of barcode.

CLONE_NPY: .npy version of CLONE_MAT

CEll_BC: path to .txt cell BC file generated from pre-processing.sh

DATASET: string of where the files came from 

FINAL_NAM_MAT: Final name of matrix.csv generated from this notebook

In [55]:
CLONE_MAT = '/datastore_share/Users/mayho/barcodes/nuclei/e193-3B/e193-3B_UMI3.csv'
CLONE_NPY = '/datastore_share/Users/mayho/barcodes/nuclei/e193-3B/e193-3B_UMI3.npy'
CELL_BCS = "/datastore_share/Users/mayho/barcodes/nuclei/e193-3B/e193-3B_whitelist.txt"
DATASET = 'e193-3B'

In [61]:
# load csv file as pandas and numpy file to do boolean filtering
clone_mat = pd.read_csv(CLONE_MAT, error_bad_lines=False, header = None)
clone_mat_np = np.load(CLONE_NPY)
# read in cell bc file
# cell_bcs = open(CELL_BCS).read().strip('\n').split('\n') #use this to read in barcodes that are already in .txt file format
cell_bcs = pd.read_csv(CELL_BCS, sep='\t', header = None)

In [57]:
# examine dimensions of the matrix
clone_mat.shape

(1314, 269)

In [42]:
# get rid of columns that label no clones. OR take out any columns where sum < 1 (i.e. does not label cell) 
multi_cc = np.sum(clone_mat_np, axis = 0)
multi_cc_bool = multi_cc >= 1
clone_mat = clone_mat.iloc[:,multi_cc_bool]
clone_mat_np = clone_mat_np[:,multi_cc_bool]
clone_mat.head()
clone_mat.shape

(1314, 259)

In [43]:
# add cell bc column
clone_mat['cellbc'] = cell_bcs.loc[:,0].tolist()
clone_mat.head()

,0,1,2,3,4,5,6,7,8,9,...,260,261,262,263,264,265,266,267,268,cellbc
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAACCCATGTACTCTG
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAACGAATCCAAGCTA
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAACGAATCGCGAAGA
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAACGCTTCGAAGTGG
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAACGCTTCTAGACAC

In [33]:
# only keep rows (cells) that sum to up to 1 or more (i.e. must contain a lineage barcode)
sum_bc = np.sum(clone_mat_np, axis = 1)
sum_bc_bool = sum_bc >= 1
clone_mat = clone_mat.iloc[sum_bc_bool, :]
clone_mat_np = clone_mat_np[sum_bc_bool,:]
clone_mat.shape
clone_mat.head()

,0,1,2,3,4,5,6,7,8,9,...,260,261,262,263,264,265,266,267,268,cellbc
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAACGCTTCGAAGTGG
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAAGTCCCATTGACCA
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AACACACAGAGCAGTC
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AACGTCACAGCCGGTT
42,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AAGCGAGCAAAGGATT

In [34]:
clone_mat.shape

(190, 260)

In [35]:
clone_mat.to_csv('/datastore_share/Users/mayho/barcodes/nuclei/e193-3B/e193-3B_sparse_matrix_UMI3.csv')